# Generated by Django 3.2.9 on 2022-05-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0003_primarykeysofimages'),
        ('country', '0003_contentcountry_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_images',
            field=models.ManyToManyField(null=True, to='relation.PrimaryKeysOfImages'),
        ),
    ]
