# Generated by Django 3.2.9 on 2022-05-27 04:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_auto_20220526_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 27, 4, 23, 17, 409434, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='deleted_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
