# Generated by Django 3.2.9 on 2022-05-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20220601_0001'),
        ('country', '0004_alter_country_country_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_info',
        ),
        migrations.AddField(
            model_name='country',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_images',
            field=models.ManyToManyField(db_table='country_images', to='gallery.Image'),
        ),
    ]
