# Generated by Django 3.2.9 on 2022-05-28 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
        ('country', '0005_auto_20220527_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_images',
        ),
        migrations.AlterField(
            model_name='contentcountry',
            name='country',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='country.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentcountry',
            name='language',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to='language.language'),
            preserve_default=False,
        ),
    ]
