# Generated by Django 3.2.9 on 2022-05-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_auto_20220528_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='country',
            name='deleted_by',
        ),
    ]
