# Generated by Django 3.2.9 on 2022-06-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_alter_country_country_images'),
        ('country', '0007_auto_20220528_1640'),
    ]

    operations = [
    ]
