# Generated by Django 3.2.9 on 2022-06-02 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_auto_20220602_1432'),
        ('language', '0002_alter_language_options'),
        ('country', '0008_merge_20220602_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='contentcountry',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.country'),
        ),
        migrations.AlterField(
            model_name='contentcountry',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.language'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_images',
            field=models.ManyToManyField(db_table='country_images', to='gallery.Image'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
