# Generated by Django 3.2.9 on 2022-05-10 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shrine', '0001_initial'),
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('price', models.FloatField(null=True)),
                ('url', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
                ('images', models.ManyToManyField(to='relation.PrimaryKeysOfImages')),
                ('shrines', models.ManyToManyField(to='shrine.Shrine')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.typetour')),
            ],
        ),
    ]
