# Generated by Django 3.2.9 on 2022-05-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20220522_2332'),
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='TypeTour',
        ),
    ]
