# Generated by Django 3.2.9 on 2022-05-26 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shrine', '0004_auto_20220526_1501'),
        ('tour', '0004_auto_20220526_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_shrines',
            field=models.ManyToManyField(db_table='tour_shrines', to='shrine.Shrine'),
        ),
        migrations.CreateModel(
            name='TourShrine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_tour_id', models.IntegerField()),
                ('shrine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shrine.shrine')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour')),
            ],
            options={
                'db_table': 'Tour_order',
            },
        ),
    ]
