# Generated by Django 3.2.9 on 2022-05-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_auto_20220526_1625'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tourshrine',
            table='tour_orders',
        ),
    ]
