# Generated by Django 3.2.9 on 2022-05-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_auto_20220527_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='deleted_by',
        ),
    ]
