# Generated by Django 3.2.9 on 2022-05-10 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
        ('shrine', '0001_initial'),
        ('tour', '0001_initial'),
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.TextField()),
                ('altText', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='country.country')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='region.region')),
                ('shrine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shrine.shrine')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.tour')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.typeimage')),
            ],
        ),
    ]
