# Generated by Django 3.2.9 on 2022-05-22 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0003_contentimage_contenttypeimage_image_typeimage'),
        ('region', '0003_contentregion_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.region'),
        ),
    ]
