# Generated by Django 3.2.9 on 2022-05-22 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0004_image_region'),
        ('shrine', '0003_contentshrine_shrine'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='shrine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shrine.shrine'),
        ),
    ]
