# Generated by Django 3.2.9 on 2022-05-22 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0005_image_shrine'),
        ('language', '0001_initial'),
        ('tour', '0003_contenttour_contenttypetour_tour_typetour'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.tour'),
        ),
        migrations.AddField(
            model_name='image',
            name='type_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.typeimage'),
        ),
        migrations.AddField(
            model_name='contenttypeimage',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.language'),
        ),
        migrations.AddField(
            model_name='contenttypeimage',
            name='type_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.typeimage'),
        ),
        migrations.AddField(
            model_name='contentimage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.image'),
        ),
        migrations.AddField(
            model_name='contentimage',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.language'),
        ),
    ]
