# Generated by Django 3.2.9 on 2022-05-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20220526_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
    ]
