# Generated by Django 3.2.9 on 2022-05-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_image_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='image',
            name='deleted_by',
        ),
    ]
