# <<<<<<< HEAD
# # Generated by Django 3.2.9 on 2022-05-31 19:01
# =======
# # Generated by Django 3.2.9 on 2022-05-29 10:22
# >>>>>>> d06a387948cc665eb06060182dc0e89d8368990c

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['id']},
        ),
    ]
