# Generated by Django 3.2.9 on 2022-05-31 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['id']},
        ),
    ]
