# Generated by Django 3.2.9 on 2022-05-22 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relation', '0003_primarykeysofimages'),
        ('country', '0003_contentcountry_country'),
        ('region', '0003_contentregion_region'),
        ('language', '0001_initial'),
        ('shrine', '0002_delete_shrine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shrine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shrine_name', models.CharField(max_length=255)),
                ('shrine_info', models.TextField()),
                ('shrine_url', models.CharField(max_length=1000)),
                ('shrine_location_longitude', models.FloatField()),
                ('shrine_location_latitude', models.FloatField()),
                ('shrine_meta_keywords', models.TextField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.country')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.region')),
                ('shrine_images', models.ManyToManyField(to='relation.PrimaryKeysOfImages')),
            ],
        ),
        migrations.CreateModel(
            name='ContentShrine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shrine_name', models.CharField(max_length=255)),
                ('shrine_info', models.TextField()),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.language')),
                ('shrine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shrine.shrine')),
            ],
        ),
    ]
