# Generated by Django 3.2.9 on 2022-05-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20220601_0001'),
        ('shrine', '0003_contentshrine_shrine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shrine',
            name='shrine_info',
        ),
        migrations.AddField(
            model_name='shrine',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shrine',
            name='shrine_images',
            field=models.ManyToManyField(db_table='shrine_images', to='gallery.Image'),
        ),
    ]
