# Generated by Django 3.2.9 on 2022-05-22 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relation', '0003_primarykeysofimages'),
        ('country', '0003_contentcountry_country'),
        ('language', '0001_initial'),
        ('region', '0002_delete_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255)),
                ('region_info', models.TextField()),
                ('region_url', models.CharField(max_length=500)),
                ('region_meta_keywords', models.TextField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.country')),
                ('region_images', models.ManyToManyField(to='relation.PrimaryKeysOfImages')),
            ],
        ),
        migrations.CreateModel(
            name='ContentRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=255)),
                ('region_info', models.TextField()),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='language.language')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.region')),
            ],
        ),
    ]
