# Generated by Django 3.2.9 on 2022-05-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20220526_1501'),
        ('region', '0003_contentregion_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='region_info',
        ),
        migrations.AlterField(
            model_name='region',
            name='region_images',
            field=models.ManyToManyField(db_table='region_table', to='gallery.Image'),
        ),
    ]
