# Generated by Django 3.2.9 on 2022-06-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0006_auto_20220528_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='created_at',
        ),
    ]
